/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MarketRouteImport } from './routes/market'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as NewsRouteImport } from './routes/news'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as WinsRouteImport } from './routes/wins'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminNewsRouteImport } from './routes/admin.news'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AuctionIdRouteImport } from './routes/auction.$id'
import { Route as CardIdRouteImport } from './routes/card.$id'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutIdRouteImport } from './routes/checkout.$id'
import { Route as MarketIndexRouteImport } from './routes/market.index'
import { Route as MarketIdRouteImport } from './routes/market.$id'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiPublicCronAuctionsRouteImport } from './routes/api/public/cron.auctions'
import { Route as ApiPublicPushDispatchRouteImport } from './routes/api/public/push.dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const WinsRoute = WinsRouteImport.update({
  id: '/wins',
  path: '/wins',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewsRoute = AdminNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AuctionIdRoute = AuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CardIdRoute = CardIdRouteImport.update({
  id: '/card/$id',
  path: '/card/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CheckoutRoute,
} as any)
const MarketIndexRoute = MarketIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketRoute,
} as any)
const MarketIdRoute = MarketIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MarketRoute,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NewsRoute,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAuctionsRoute = ApiPublicCronAuctionsRouteImport.update({
  id: '/api/public/cron/auctions',
  path: '/api/public/cron/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushDispatchRoute = ApiPublicPushDispatchRouteImport.update({
  id: '/api/public/push/dispatch',
  path: '/api/public/push/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/market': typeof MarketRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRoute
  '/wins': typeof WinsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/auction/$id': typeof AuctionIdRoute
  '/card/$id': typeof CardIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/market/$id': typeof MarketIdRoute
  '/news/$id': typeof NewsIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/market/': typeof MarketIndexRoute
  '/api/public/cron/auctions': typeof ApiPublicCronAuctionsRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/marketplace': typeof MarketplaceRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRoute
  '/wins': typeof WinsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/auction/$id': typeof AuctionIdRoute
  '/card/$id': typeof CardIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/market/$id': typeof MarketIdRoute
  '/news/$id': typeof NewsIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/market': typeof MarketIndexRoute
  '/api/public/cron/auctions': typeof ApiPublicCronAuctionsRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auctions': typeof AuctionsRoute
  '/auth': typeof AuthRoute
  '/market': typeof MarketRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/news': typeof NewsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vault': typeof VaultRoute
  '/wins': typeof WinsRoute
  '/wishlist': typeof WishlistRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/news': typeof AdminNewsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/auction/$id': typeof AuctionIdRoute
  '/card/$id': typeof CardIdRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/market/$id': typeof MarketIdRoute
  '/news/$id': typeof NewsIdRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$id': typeof ProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/market/': typeof MarketIndexRoute
  '/api/public/cron/auctions': typeof ApiPublicCronAuctionsRoute
  '/api/public/push/dispatch': typeof ApiPublicPushDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auctions'
    | '/auth'
    | '/market'
    | '/marketplace'
    | '/news'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/vault'
    | '/wins'
    | '/wishlist'
    | '/admin/members'
    | '/admin/news'
    | '/admin/orders'
    | '/auction/$id'
    | '/card/$id'
    | '/checkout/$id'
    | '/market/$id'
    | '/news/$id'
    | '/order/$id'
    | '/product/$id'
    | '/admin/'
    | '/checkout/'
    | '/market/'
    | '/api/public/cron/auctions'
    | '/api/public/push/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/auth'
    | '/marketplace'
    | '/news'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/vault'
    | '/wins'
    | '/wishlist'
    | '/admin/members'
    | '/admin/news'
    | '/admin/orders'
    | '/auction/$id'
    | '/card/$id'
    | '/checkout/$id'
    | '/market/$id'
    | '/news/$id'
    | '/order/$id'
    | '/product/$id'
    | '/admin'
    | '/checkout'
    | '/market'
    | '/api/public/cron/auctions'
    | '/api/public/push/dispatch'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auctions'
    | '/auth'
    | '/market'
    | '/marketplace'
    | '/news'
    | '/profile'
    | '/shop'
    | '/sitemap.xml'
    | '/vault'
    | '/wins'
    | '/wishlist'
    | '/admin/members'
    | '/admin/news'
    | '/admin/orders'
    | '/auction/$id'
    | '/card/$id'
    | '/checkout/$id'
    | '/market/$id'
    | '/news/$id'
    | '/order/$id'
    | '/product/$id'
    | '/admin/'
    | '/checkout/'
    | '/market/'
    | '/api/public/cron/auctions'
    | '/api/public/push/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuctionsRoute: typeof AuctionsRoute
  AuthRoute: typeof AuthRoute
  MarketRoute: typeof MarketRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  NewsRoute: typeof NewsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VaultRoute: typeof VaultRoute
  WinsRoute: typeof WinsRoute
  WishlistRoute: typeof WishlistRoute
  AuctionIdRoute: typeof AuctionIdRoute
  CardIdRoute: typeof CardIdRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductIdRoute: typeof ProductIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  ApiPublicCronAuctionsRoute: typeof ApiPublicCronAuctionsRoute
  ApiPublicPushDispatchRoute: typeof ApiPublicPushDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wins': {
      id: '/wins'
      path: '/wins'
      fullPath: '/wins'
      preLoaderRoute: typeof WinsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/news': {
      id: '/admin/news'
      path: '/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auction/$id': {
      id: '/auction/$id'
      path: '/auction/$id'
      fullPath: '/auction/$id'
      preLoaderRoute: typeof AuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/card/$id': {
      id: '/card/$id'
      path: '/card/$id'
      fullPath: '/card/$id'
      preLoaderRoute: typeof CardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/market/': {
      id: '/market/'
      path: '/'
      fullPath: '/market/'
      preLoaderRoute: typeof MarketIndexRouteImport
      parentRoute: typeof MarketRoute
    }
    '/market/$id': {
      id: '/market/$id'
      path: '/$id'
      fullPath: '/market/$id'
      preLoaderRoute: typeof MarketIdRouteImport
      parentRoute: typeof MarketRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/auctions': {
      id: '/api/public/cron/auctions'
      path: '/api/public/cron/auctions'
      fullPath: '/api/public/cron/auctions'
      preLoaderRoute: typeof ApiPublicCronAuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/dispatch': {
      id: '/api/public/push/dispatch'
      path: '/api/public/push/dispatch'
      fullPath: '/api/public/push/dispatch'
      preLoaderRoute: typeof ApiPublicPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminMembersRoute: typeof AdminMembersRoute
  AdminNewsRoute: typeof AdminNewsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMembersRoute: AdminMembersRoute,
  AdminNewsRoute: AdminNewsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MarketRouteChildren {
  MarketIdRoute: typeof MarketIdRoute
  MarketIndexRoute: typeof MarketIndexRoute
}

const MarketRouteChildren: MarketRouteChildren = {
  MarketIdRoute: MarketIdRoute,
  MarketIndexRoute: MarketIndexRoute,
}

const MarketRouteWithChildren =
  MarketRoute._addFileChildren(MarketRouteChildren)

interface NewsRouteChildren {
  NewsIdRoute: typeof NewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsIdRoute: NewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuctionsRoute: AuctionsRoute,
  AuthRoute: AuthRoute,
  MarketRoute: MarketRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  NewsRoute: NewsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VaultRoute: VaultRoute,
  WinsRoute: WinsRoute,
  WishlistRoute: WishlistRoute,
  AuctionIdRoute: AuctionIdRoute,
  CardIdRoute: CardIdRoute,
  OrderIdRoute: OrderIdRoute,
  ProductIdRoute: ProductIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  ApiPublicCronAuctionsRoute: ApiPublicCronAuctionsRoute,
  ApiPublicPushDispatchRoute: ApiPublicPushDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
